Feature#10 main checker view
BC-MAY-21-ROR/kata-06-el-reloj-checador-k6-ca-reilero-04 pull request #18
Opened 2022-09-14 21:31 UTC by JorgeRodz

# Description
What did you implemented/Why did you implemented this:
- Implement the check-in and check-out functionality in order to register an assistant
- Implement 'flash_messages' in order to display messages to the user
- Add 'live clock time' using JS vanilla

 Examples:
 - Check-in a user and store employee_id, store_id, check_in (datetime), check_out
 - Display live-clock in order to show the user at what time it is
 - Display messages in order to inform the user the form submit state

  ## Screenshots
![attendances](https://user-images.githubusercontent.com/13999498/190266002-a10910ff-ee1b-4e36-86e3-d9da5f17a849.png)

![check-in_registration](https://user-images.githubusercontent.com/13999498/190266023-4038c011-b552-4ace-b558-f64eeacefde9.gif)
![check-out_registration](https://user-images.githubusercontent.com/13999498/190266029-50a3236a-d409-4a55-a0e4-f9252b3a177a.gif)

2022-09-14 21:49 UTC, OswaldoPineda requested changes
let me know if you have any doubt but pls attend all the comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/assets/stylesheets/pages.scss
> +
it would be better to create a new file only for variables like color or fonts, pls refactor this

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/assets/stylesheets/pages.scss
> +      //width: 85px;
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/assets/stylesheets/pages.scss
> +    //font-family: 'Menlo', monospace;
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/assets/stylesheets/pages.scss
> +      // border: 1px solid red;
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/assets/stylesheets/pages.scss
> +}
add a final line this warning is because this file doesn't have a line at the end

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +    # Where return an array of objects, so we save the first one and thus the only one object because we have only allow to have just check_in per day
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +    # byebug
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +      # attendance new instance
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +    if params[:commit] == "Check-in"
you could refactor this by doing something like
```

return if params[:commit] != "Check-in"
# resto of your code
```

on this way you removed the nesting level of the rest of this method

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +      # byebug
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +        return
your method has a lot of lines pls refactor this maybe in small methods and call them here

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +      # byebug
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +      # byebug
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +    if params[:commit] == "Check-out"
same as the above comment related to the nesting level and refactor

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
> +    # @attendance = Attendance.find(params[:id])
delete unnecessary comments

2022-09-14 21:49 UTC, OswaldoPineda commented on time_checker/app/controllers/attendances_controller.rb
>  end
delete unnecessary comments

2022-09-14 21:59 UTC, JuanequeX requested changes

2022-09-14 21:59 UTC, JuanequeX commented on time_checker/app/assets/stylesheets/pages.scss
> +  background-color: #232323;
sort this block alphabetically and change your background color for a variable.

2022-09-14 21:59 UTC, JuanequeX commented on time_checker/app/assets/stylesheets/pages.scss
> +    z-index: 9;
same here, sort alphabetically and change your color for a variable.

2022-09-14 21:59 UTC, JuanequeX commented on time_checker/app/assets/stylesheets/pages.scss
> +    border-radius: 10px;
sort it and change this color for a variable

2022-09-14 21:59 UTC, JuanequeX commented on time_checker/app/assets/stylesheets/pages.scss
> +      justify-content: center;
sort this block too

2022-09-14 21:59 UTC, JuanequeX commented on time_checker/app/assets/stylesheets/pages.scss
> +}
i agree with @OswaldoPineda

2022-09-14 21:59 UTC, JuanequeX commented on time_checker/app/controllers/attendances_controller.rb
> +    #hol
delete this comment

2022-09-14 21:59 UTC, JuanequeX commented on time_checker/app/views/employees/new.html.erb
> +</div>
Add a blank line here

2022-09-14 21:59 UTC, JuanequeX commented on time_checker/app/views/pages/_clock.html.erb
> +</div>
Add a blank line here

2022-09-14 21:59 UTC, JuanequeX commented on time_checker/app/views/stores/new.html.erb
> +</div>
Add an blank line here!

2022-09-14 22:23 UTC, juperameza requested changes

2022-09-14 22:23 UTC, juperameza commented on time_checker/app/controllers/attendances_controller.rb
> -    end
Try to delete trailing blank spaces

2022-09-14 22:23 UTC, juperameza commented on time_checker/app/controllers/attendances_controller.rb
> -    end
I use this vs extension https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces}

2022-09-14 23:42 UTC, dagp-ucol commented on time_checker/app/controllers/attendances_controller.rb
> +        return
We tried but we could not, so we made an issue to work on it later.

https://github.com/BC-MAY-21-ROR/kata-06-el-reloj-checador-k6-ca-reilero-04/issues/20

2022-09-14 23:50 UTC, dagp-ucol commented on time_checker/app/controllers/attendances_controller.rb
> -    end
## Your extension is not working haha.

![image](https://user-images.githubusercontent.com/73558208/190282187-990b5c7e-a92a-4c0a-85da-13d2674fc14d.png)

2022-09-14 23:51 UTC, juperameza commented on time_checker/app/controllers/attendances_controller.rb
> -    end
Fixed I added a bracket. Lol

2022-09-15 00:13 UTC, dagp-ucol commented on time_checker/app/controllers/attendances_controller.rb
> -    end
XD Thanks :D

2022-09-15 15:09 UTC, JuanequeX requested changes

2022-09-15 15:09 UTC, JuanequeX commented on time_checker/app/assets/stylesheets/pages.scss
> +@import "./variables/colors.scss";
if they are use the pattern 7-1 in scss, are not necessary import this file.

2022-09-15 15:09 UTC, JuanequeX commented on time_checker/app/assets/stylesheets/pages.scss
> +@import url('https://fonts.googleapis.com/css?family=Orbitron');
This import should be in a file called `fonts.scss`

2022-09-15 15:09 UTC, JuanequeX commented on time_checker/app/assets/stylesheets/pages.scss
> +
All of this variables shouldn't exist here, it's will be declared in other file, this breakpoints in `mixins.scss` file  for example

2022-09-16 01:21 UTC, juperameza requested changes

2022-09-16 01:21 UTC, juperameza commented on time_checker/app/controllers/attendances_controller.rb
> +    # @store.destroy
Don't leave unused code 🙅🙅

2022-09-16 01:21 UTC, juperameza commented on time_checker/app/controllers/employees_controller.rb
> +    if @employee.update(params.require(:employee).permit(:first_name, :last_name, :email, :position, :working,
Here I recommend you use another method to define your strong Params since it's being used twice and repeating code
[Like this!](https://api.rubyonrails.org/classes/ActionController/StrongParameters.html)

2022-09-19 21:47 UTC, JorgeRodz commented on time_checker/app/controllers/attendances_controller.rb
> +    # @store.destroy
We already delete that code because we no longer use it.

2022-09-19 21:48 UTC, JorgeRodz commented on time_checker/app/controllers/employees_controller.rb
> +    if @employee.update(params.require(:employee).permit(:first_name, :last_name, :email, :position, :working,
Refactor done on every controller.

2022-09-19 21:56 UTC, iMartinDav approved these changes
LGTM

2022-09-19 22:56 UTC, iMartinDav approved these changes
Looks good

2022-09-19 22:57 UTC, willcab approved these changes
good job

2022-09-20 00:31 UTC, juperameza approved these changes
LGMT

2022-09-20 14:14 UTC, OswaldoPineda approved these changes
LGTM 👍🏽

2022-09-20 21:28 UTC, JuanequeX approved these changes
LGTM

2022-09-20 21:29 UTC, merged