Feature#23 add monthly attendance report
BC-MAY-21-ROR/kata-06-el-reloj-checador-k6-ca-reilero-04 pull request #26
Opened 2022-09-26 23:20 UTC by GustavoHiguera

# Description
We implemented the daily and monthly reports that the admin can do.
We created the views and the routes for each report.

 Examples:
The changes complete 3 milestones of the kata.

  ## Screenshots
![kata-06-reports](https://user-images.githubusercontent.com/73560278/192397489-235ab09c-0acb-413e-8691-5e5aa6496a8f.gif)

2022-09-26 23:26 UTC, willcab approved these changes
LGTM 👍

2022-09-26 23:27 UTC, Dcastanedaan approved these changes
Good job!!

2022-09-26 23:44 UTC, juperameza approved these changes
LGTM!

2022-09-26 23:47 UTC, OswaldoPineda requested changes
Just some comments about refactor

2022-09-26 23:47 UTC, OswaldoPineda commented on time_checker/app/controllers/stores_controller.rb
> +    start_day = date
did you try something like:
```
start_day = "#{params[:month]}-01".to_date
```

2022-09-26 23:47 UTC, OswaldoPineda commented on time_checker/app/controllers/stores_controller.rb
> +    start_day = date
did you try something like:
```
start_day = "#{params[:month]}-01".to_date
```

2022-09-26 23:47 UTC, OswaldoPineda commented on time_checker/app/controllers/stores_controller.rb
> +  def reports_abs_by_month_date
this is basically the same than the `reports_avg_time_by_month_date` pls refactor these methods
always remember the DRY(don't repeat yourself)

2022-09-26 23:47 UTC, OswaldoPineda commented on time_checker/app/views/stores/reports.html.erb
> +</div>
add a final blank line here

2022-09-26 23:47 UTC, OswaldoPineda commented on time_checker/app/views/stores/reports_avg_time_by_month.html.erb
> +<% end %>
add a final blank line here

2022-09-27 21:14 UTC, JuanequeX commented
khe rayos 5,000+ changes?

2022-09-27 21:15 UTC, CalixtoLopez commented on time_checker/app/controllers/stores_controller.rb
> +    start_day = date
Refactor code

2022-09-27 21:15 UTC, CalixtoLopez commented on time_checker/app/controllers/stores_controller.rb
> +    start_day = date
Refactor code

2022-09-27 21:16 UTC, CalixtoLopez commented on time_checker/app/controllers/stores_controller.rb
> +  def reports_abs_by_month_date
Refactor code

2022-09-27 21:22 UTC, GustavoHiguera commented
> khe rayos 5,000+ changes?

Es que sacamos los archivos de la carpeta que genera el rails a la carpeta del repositorio.

2022-09-27 21:23 UTC, JuanequeX commented
> > khe rayos 5,000+ changes?
> 
> Es que sacamos los archivos de la carpeta que genera el rails a la carpeta del repositorio.

and what is the reason of this change?

I think, if you will planning solved the `Feature#23 add monthly attendance report`, they only should solve this specific feature and create another PR to fix your rubocop problems.

2022-09-27 21:27 UTC, dagp-ucol commented
### Hi

We did this because since these are the last few days and lately pull requests take time to be approved, we made this decision.

Although we understand that it was not the right thing to do and it will not happen again.

2022-09-27 21:33 UTC, JuanequeX commented
> ### Hi!
> We did this because since these are the last few days and lately pull requests take time to be approved, we made this decision.
> 
> Although we understand that it was not the right thing to do and it will not happen again.
> 
> Also, we did not do this to solve any existing problem, but to have a good practice on our project.

I don't know guys, i know that in some cases is dificult to have a review, but integrate good practices in a this way it is not a good practice

2022-09-27 21:38 UTC, dagp-ucol commented
> I don't know guys, i know that in some cases is dificult to have a review, but integrate good practices in a this way it is not a good practice

Thank you [JuanequeX](https://github.com/JuanequeX) for the feedback, we have done a rollback and we will do it in the correct way.

2022-09-27 21:45 UTC, merged