Feature#25 fix styles and html structure
BC-MAY-21-ROR/kata-06-el-reloj-checador-k6-ca-reilero-04 pull request #27
Opened 2022-09-27 22:39 UTC by dagp-ucol

# Description
- Change style and add new html structure.
- Fix flash messages with correct color.
- Add navigation bar in admin views.

# Examples:
- Organize views with more buttons and nv bar.
- When doing a correct action a flash message appears in green color.
- When doing an incorrect action a flash message appears in red color.

## Screenshots
![Peek 27-09-2022 17-36](https://user-images.githubusercontent.com/73558208/192649969-8a204cc3-9d0b-465b-80bf-8ed4a2b01176.gif)

2022-09-27 22:46 UTC, juperameza approved these changes
LGTM

2022-09-27 22:51 UTC, OswaldoPineda approved these changes

2022-09-27 23:26 UTC, JuanequeX requested changes

2022-09-27 23:26 UTC, JuanequeX commented on time_checker/app/views/employees/index.html.erb
> +          <% end %>
i think that this `</tr>` label are closed it at wrong way

2022-09-27 23:26 UTC, JuanequeX commented on time_checker/app/views/stores/index.html.erb
> +        <% end %>
i think that this `</tr>` label are closed it at wrong way

2022-09-27 23:26 UTC, JuanequeX commented on time_checker/app/views/stores/reports_att_by_day.html.erb
> +              <th scope="col">Submit</th>
please,  fix the identation on this block

2022-09-27 23:26 UTC, JuanequeX commented on time_checker/app/views/stores/reports_att_by_day_date.html.erb
>      <% end %>
i think that this `</tr>` label are closed it at wrong way

2022-09-27 23:26 UTC, JuanequeX commented on time_checker/config/database.yml
> +  password: Pandecomala12345678
this file will be should exist only on yours local computers, please add it on your `.gitignore` and add an `database.example.yml`

2022-09-27 23:36 UTC, CalixtoLopez commented on time_checker/app/views/stores/reports_att_by_day.html.erb
> +              <th scope="col">Submit</th>
ok

2022-09-27 23:37 UTC, CalixtoLopez commented on time_checker/app/views/stores/index.html.erb
> +        <% end %>
ok

2022-09-27 23:38 UTC, CalixtoLopez commented on time_checker/app/views/stores/reports_att_by_day.html.erb
> +              <th scope="col">Submit</th>
ok

2022-09-27 23:44 UTC, CalixtoLopez commented on time_checker/app/views/stores/reports_att_by_day_date.html.erb
>      <% end %>
Ok

2022-09-27 23:47 UTC, JorgeRodz commented on time_checker/app/views/employees/index.html.erb
> +          <% end %>
It should be there, otherwise all the employees are show up in one line.  
![image](https://user-images.githubusercontent.com/13999498/192656848-68db3223-5475-4c91-93e1-efe81f9f70b3.png)

2022-09-28 14:53 UTC, JuanequeX commented on time_checker/app/views/employees/index.html.erb
> +          <% end %>
Otherwise this label are outside

<img width="429" alt="image" src="https://user-images.githubusercontent.com/50384228/192811618-009ba862-3bb1-40a0-9741-7b04c951d6ac.png">

2022-09-28 21:02 UTC, GustavoHiguera commented on time_checker/app/views/employees/index.html.erb
> +          <% end %>
Thank you, we corrected it. :+1:

2022-09-28 22:32 UTC, JuanequeX requested changes

2022-09-28 22:32 UTC, JuanequeX commented on time_checker/.gitignore
> +/config/database.yml
Add a blnak line here

2022-09-28 22:32 UTC, JuanequeX commented on time_checker/app/views/stores/reports_abs_by_month.html.erb
> +            <th scope="col">Submit</th>
fix this identation

2022-09-28 22:32 UTC, JuanequeX commented on time_checker/app/views/stores/reports_att_by_day_date.html.erb
>        <% @reports.each do |report| %>
fix this label opening

2022-09-28 22:32 UTC, JuanequeX commented on time_checker/app/views/stores/reports_avg_time_by_month.html.erb
> +            </tr>
fix this identation

2022-09-28 22:49 UTC, JuanequeX approved these changes
LGTM

2022-09-28 22:56 UTC, elioflo approved these changes
GJ

2022-09-28 22:57 UTC, EduardoBriceno89 approved these changes
LGTM

2022-09-28 22:57 UTC, jorgeboris approved these changes

2022-09-28 22:58 UTC, merged

2022-09-28 22:59 UTC, LuisFLara commented on time_checker/app/views/stores/reports.html.erb
> +			<thead>
check the indet to be constant in all files

2022-09-28 23:02 UTC, LuisFLara commented on time_checker/app/views/stores/show.html.erb
> +          <% @employees = @store.employees %>
is this assignation beign used in other place? maybe you can use this 
```Ruby
<% @store.employees.each do |employee| %>
```

2022-09-28 23:03 UTC, LuisFLara approved these changes
I left little style comments, but looks good 👍